#!/bin/sh
set -eu

# Xcode Cloud runs this immediately after the repo is cloned, before any
# Xcode resolution. Working directory: $CI_PRIMARY_REPOSITORY_PATH/ci_scripts.
# We rewrite to repo root so paths match local dev.

# test-without-building runs on a fresh runner that never had a clone;
# the post-clone hook still fires there, but with no repo to act on.
# Skip cleanly so `set -eu` doesn't kill the pipeline.
if [ -z "${CI_PRIMARY_REPOSITORY_PATH:-}" ]; then
  echo "ci_post_clone: no repo on this runner (test-without-building); nothing to do"
  exit 0
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Config/Secrets.xcconfig is gitignored locally. In the cloud we synthesize
# it from workflow environment variables (set in App Store Connect →
# Xcode Cloud → Workflow → Environment).
#
# Required for any cloud build:
#   AI_RELAY_BASE_URL              e.g. https:/$()/relay.example.com
#
# Optional:
#   AI_RELAY_BEARER_TOKEN          shared secret embedded into the binary.
#                                  Omit to use the per-device flow: the
#                                  app calls /bootstrap or /offline/exchange
#                                  (both unauthenticated) and stores the
#                                  per-device key returned by the server
#                                  in RelayAccessRepository. After that,
#                                  AppConfiguration.resolvedRelayBearerToken
#                                  falls back to the stored key.
#   AI_RELAY_ALLOW_INSECURE_TLS    YES only if relay uses self-signed cert.
#   APP_GROUP_IDENTIFIER           group.your.company.aichat
#
# AI_BACKEND_MODE is pinned to relay for cloud builds; direct mode would
# require shipping a Gemini key in the binary, which we never do.

: "${AI_RELAY_BASE_URL:?missing required env var AI_RELAY_BASE_URL}"

OUT="Config/Secrets.xcconfig"

{
  echo "// Generated by ci_scripts/ci_post_clone.sh — do not edit."
  echo "AI_BACKEND_MODE = relay"
  echo "AI_RELAY_BASE_URL = ${AI_RELAY_BASE_URL}"
  if [ -n "${AI_RELAY_BEARER_TOKEN:-}" ]; then
    echo "AI_RELAY_BEARER_TOKEN = ${AI_RELAY_BEARER_TOKEN}"
  fi
  if [ "${AI_RELAY_ALLOW_INSECURE_TLS:-}" = "YES" ]; then
    echo "AI_RELAY_ALLOW_INSECURE_TLS = YES"
  fi
  if [ -n "${APP_GROUP_IDENTIFIER:-}" ]; then
    echo "APP_GROUP_IDENTIFIER = ${APP_GROUP_IDENTIFIER}"
  fi
} > "$OUT"

if [ -n "${AI_RELAY_BEARER_TOKEN:-}" ]; then
  echo "ci_post_clone: wrote $OUT (AI_BACKEND_MODE=relay, embedded bearer)"
else
  echo "ci_post_clone: wrote $OUT (AI_BACKEND_MODE=relay, no embedded bearer; per-device key via bootstrap/exchange)"
fi
