#!/bin/sh
set -eu

# Xcode Cloud runs this immediately after the repo is cloned, before any
# Xcode resolution. Working directory: $CI_PRIMARY_REPOSITORY_PATH/ci_scripts.
# We rewrite to repo root so paths match local dev.

# test-without-building runs on a fresh runner that never had a clone;
# the post-clone hook still fires there, but with no repo to act on.
# Skip cleanly so `set -eu` doesn't kill the pipeline.
if [ -z "${CI_PRIMARY_REPOSITORY_PATH:-}" ]; then
  echo "ci_post_clone: no repo on this runner (test-without-building); nothing to do"
  exit 0
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Config/Secrets.xcconfig is gitignored locally. In the cloud we synthesize
# it from workflow environment variables (set in App Store Connect →
# Xcode Cloud → Workflow → Environment).
#
# Optional relay backend (recommended for production):
#   AI_RELAY_BASE_URL              e.g. https:/$()/relay.example.com
#   AI_RELAY_BEARER_TOKEN          shared secret for relay auth
#   AI_RELAY_ALLOW_INSECURE_TLS    YES only if relay uses self-signed cert
#
# Optional general:
#   APP_GROUP_IDENTIFIER           group.your.company.aichat
#
# Behavior:
#   - If both AI_RELAY_BASE_URL and AI_RELAY_BEARER_TOKEN are set, the
#     build is pinned to `relay` mode and both values are written into
#     Secrets.xcconfig. This is the supported production path.
#   - If either is missing, the build falls back to `direct` mode with
#     no embedded API key. Users provide their own Gemini key (or paste
#     an activation code that grants relay access) at runtime via the
#     in-app settings. This unblocks TestFlight uploads for builds where
#     the operator hasn't provisioned a relay yet.

OUT="Config/Secrets.xcconfig"

if [ -n "${AI_RELAY_BASE_URL:-}" ] && [ -n "${AI_RELAY_BEARER_TOKEN:-}" ]; then
  {
    echo "// Generated by ci_scripts/ci_post_clone.sh — do not edit."
    echo "AI_BACKEND_MODE = relay"
    echo "AI_RELAY_BASE_URL = ${AI_RELAY_BASE_URL}"
    echo "AI_RELAY_BEARER_TOKEN = ${AI_RELAY_BEARER_TOKEN}"
    if [ "${AI_RELAY_ALLOW_INSECURE_TLS:-}" = "YES" ]; then
      echo "AI_RELAY_ALLOW_INSECURE_TLS = YES"
    fi
    if [ -n "${APP_GROUP_IDENTIFIER:-}" ]; then
      echo "APP_GROUP_IDENTIFIER = ${APP_GROUP_IDENTIFIER}"
    fi
  } > "$OUT"
  echo "ci_post_clone: wrote $OUT (AI_BACKEND_MODE=relay)"
else
  {
    echo "// Generated by ci_scripts/ci_post_clone.sh — do not edit."
    echo "// Relay env vars not set; defaulting to direct mode without"
    echo "// an embedded API key. Configure activation in-app at runtime."
    echo "AI_BACKEND_MODE = direct"
    if [ -n "${APP_GROUP_IDENTIFIER:-}" ]; then
      echo "APP_GROUP_IDENTIFIER = ${APP_GROUP_IDENTIFIER}"
    fi
  } > "$OUT"
  echo "ci_post_clone: wrote $OUT (AI_BACKEND_MODE=direct, no relay configured)"
fi
