#!/bin/sh
set -eu

# Xcode Cloud runs this immediately after the repo is cloned, before any
# Xcode resolution. Working directory: $CI_PRIMARY_REPOSITORY_PATH/ci_scripts.
# We rewrite to repo root so paths match local dev.

# test-without-building runs on a fresh runner that never had a clone;
# the post-clone hook still fires there, but with no repo to act on.
# Skip cleanly so `set -eu` doesn't kill the pipeline.
if [ -z "${CI_PRIMARY_REPOSITORY_PATH:-}" ]; then
  echo "ci_post_clone: no repo on this runner (test-without-building); nothing to do"
  exit 0
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Config/Secrets.xcconfig is gitignored locally. In the cloud we synthesize
# it from workflow environment variables (set in App Store Connect →
# Xcode Cloud → Workflow → Environment). Required keys:
#
#   AI_RELAY_BASE_URL          e.g. https:/$()/relay.example.com
#
# Optional:
#   AI_RELAY_ALLOW_INSECURE_TLS   YES only if relay uses self-signed cert
#   APP_GROUP_IDENTIFIER          group.your.company.aichat
#
: "${AI_RELAY_BASE_URL:?missing required env var AI_RELAY_BASE_URL}"

OUT="Config/Secrets.xcconfig"

{
  echo "// Generated by ci_scripts/ci_post_clone.sh — do not edit."
  echo "AI_RELAY_BASE_URL = ${AI_RELAY_BASE_URL}"
  if [ "${AI_RELAY_ALLOW_INSECURE_TLS:-}" = "YES" ]; then
    echo "AI_RELAY_ALLOW_INSECURE_TLS = YES"
  fi
  if [ -n "${APP_GROUP_IDENTIFIER:-}" ]; then
    echo "APP_GROUP_IDENTIFIER = ${APP_GROUP_IDENTIFIER}"
  fi
} > "$OUT"

echo "ci_post_clone: wrote $OUT (relay-only)"
