import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material Design 3 roles wired to CSS variables (see src/styles/m3-tokens.css).
        primary: "rgb(var(--md-sys-color-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--md-sys-color-on-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--md-sys-color-primary-container) / <alpha-value>)",
        "on-primary-container": "rgb(var(--md-sys-color-on-primary-container) / <alpha-value>)",
        secondary: "rgb(var(--md-sys-color-secondary) / <alpha-value>)",
        "on-secondary": "rgb(var(--md-sys-color-on-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--md-sys-color-secondary-container) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--md-sys-color-on-secondary-container) / <alpha-value>)",
        tertiary: "rgb(var(--md-sys-color-tertiary) / <alpha-value>)",
        "on-tertiary": "rgb(var(--md-sys-color-on-tertiary) / <alpha-value>)",
        "tertiary-container": "rgb(var(--md-sys-color-tertiary-container) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--md-sys-color-on-tertiary-container) / <alpha-value>)",
        error: "rgb(var(--md-sys-color-error) / <alpha-value>)",
        "on-error": "rgb(var(--md-sys-color-on-error) / <alpha-value>)",
        "error-container": "rgb(var(--md-sys-color-error-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--md-sys-color-on-error-container) / <alpha-value>)",
        surface: "rgb(var(--md-sys-color-surface) / <alpha-value>)",
        "on-surface": "rgb(var(--md-sys-color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--md-sys-color-on-surface-variant) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--md-sys-color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--md-sys-color-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--md-sys-color-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--md-sys-color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--md-sys-color-surface-container-highest) / <alpha-value>)",
        outline: "rgb(var(--md-sys-color-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--md-sys-color-outline-variant) / <alpha-value>)",
        inverse: "rgb(var(--md-sys-color-inverse-surface) / <alpha-value>)",
        "on-inverse": "rgb(var(--md-sys-color-inverse-on-surface) / <alpha-value>)",
        "inverse-primary": "rgb(var(--md-sys-color-inverse-primary) / <alpha-value>)",
        scrim: "rgb(var(--md-sys-color-scrim) / <alpha-value>)",
      },
      borderRadius: {
        "m3-none": "0",
        "m3-xs": "4px",
        "m3-sm": "8px",
        "m3-md": "12px",
        "m3-lg": "16px",
        "m3-xl": "28px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        // Material Design 3 type scale.
        "m3-display-l": ["57px", { lineHeight: "64px", letterSpacing: "-0.25px" }],
        "m3-display-m": ["45px", { lineHeight: "52px" }],
        "m3-display-s": ["36px", { lineHeight: "44px" }],
        "m3-headline-l": ["32px", { lineHeight: "40px" }],
        "m3-headline-m": ["28px", { lineHeight: "36px" }],
        "m3-headline-s": ["24px", { lineHeight: "32px" }],
        "m3-title-l": ["22px", { lineHeight: "28px" }],
        "m3-title-m": ["16px", { lineHeight: "24px", letterSpacing: "0.15px" }],
        "m3-title-s": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "m3-label-l": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "m3-label-m": ["12px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "m3-label-s": ["11px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "m3-body-l": ["16px", { lineHeight: "24px", letterSpacing: "0.5px" }],
        "m3-body-m": ["14px", { lineHeight: "20px", letterSpacing: "0.25px" }],
        "m3-body-s": ["12px", { lineHeight: "16px", letterSpacing: "0.4px" }],
      },
      transitionTimingFunction: {
        "m3-standard": "cubic-bezier(0.2, 0, 0, 1)",
        "m3-emphasized": "cubic-bezier(0.2, 0, 0, 1)",
        "m3-emphasized-decel": "cubic-bezier(0.05, 0.7, 0.1, 1)",
        "m3-emphasized-accel": "cubic-bezier(0.3, 0, 0.8, 0.15)",
      },
      transitionDuration: {
        "m3-short1": "50ms",
        "m3-short2": "100ms",
        "m3-short3": "150ms",
        "m3-short4": "200ms",
        "m3-medium1": "250ms",
        "m3-medium2": "300ms",
        "m3-medium3": "350ms",
        "m3-medium4": "400ms",
        "m3-long1": "450ms",
        "m3-long2": "500ms",
      },
    },
  },
  plugins: [],
};

export default config;
